# 项目相关配置
shangtong:
  # 名称
  name: Shangtong
  # 版本
  version: 3.3.0
  # 版权年份
  copyrightYear: 2019
  # 文件路径
#  profile: D:/imgs/media/
  profile: /var/www/static/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.ruoyi: error
    org.springframework: error

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: hr
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  # redis 配置信息
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: db.rerunsoft.cn #db.rerunsoft.cn
    port: 6379
    password: Rerunsoft@321.redis.com # 密码（默认为空） Rerunsoft@321.redis.com
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  autoRuntimeDialect: true
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认一天(60*24分钟)）
    expireTime: 1440
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen: 
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.project.stock
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: tb_

#发短信
  # 短信网关
sms:
  beanName: smsSendService
  url: http://www.api.zthysms.com/sendSms.do
  username: hnyrkjhy
  password: tGIDtT
  prefix: 【商砼帮】验证码
  suffix: 。

#JPush 推送设置
jpush:
  appkey: 9f11cf64b931f723e687832f
  mastersecret: 09be05037618f4029da43ee9

#商砼站默认起点坐标
project:
  demo: false
  redis_website_pre: ZKHR_
  # 博力商砼站
#  lon : 114.425952
#  lat : 35.094117
  # 博力商砼站-终点南关县政府(不选择就默认)
  endLng: 114.427955
  endLat: 35.006119
#  lon : 113.770006
#  lat : 34.727687
  #富田财富广场起点
#  lon : 113.769995
#  lat : 34.727561
  #富田财富广场起点
  lon : 114.983261
  lat : 33.420555
  # 地图选点  114.426039,35.093114
#在起点多少米范围内都算是起点
  startDistance : 300
#在终点多少米范围内都算是起点
  endDistance : 300
#1.1分钟内(getLonLatByMin的值)行驶的距离不超过100米,就认为是车辆停止状态
  warningDistance : 100
#获取多少分钟以内的坐标记录
  getLonLatByMin : 1
#一顿的折合方率
  equalRate: 0.420168

locator: #定位器
  appid: 18236416598
  secret: ^wSnXiX8bMk4IUOM16WaWPGo#b^ISq%m

